### PR TITLE
Remove compatibility with Cemuhook and fix exports

### PR DESCRIPTION
**Pull request by Crementif**
Fixes https://github.com/cemu-project/Cemu/issues/31.

Also switches to an in-line way of exporting symbols.

### CODE REVIEW

**Comment by ArtemisX64** [comment]
I was planning on doing something similar. But cool

**Comment by Tachi107** [comment]
`__declspec(dllexport)`'s GCC equivalent is `__attribute__ ((visibility ("default")))`, but I don't know if it is relevant here.

**Comment by ArbestRi** [comment]
Cemuhook is pretty much no longer needed for Cemu, so that's a good sign that Cemuhook is getting abandoned.

**Comment by Exzap** [comment]
Looks good.
End of an era. RIP Cemuhook

**Comment by Crementif** [comment]
> `__declspec(dllexport)`'s GCC equivalent is `__attribute__ ((visibility ("default")))`, but I don't know if it is relevant here.

Yeah, I'll make a PR addressing that tomorrow.

**Pull request merged**
