### PR TITLE
UI addons

### PR DESCRIPTION
**Pull request by SSimco**
Add UI options to open the UserDataPath folder and remove shader caches.

### CODE REVIEW

**Comment by qurious-pixel** [comment]
image

**Comment by Crementif** [comment]
The Open Cemu folder option was long overdue indeed so it's nice to see it being PRed.

I do wonder if three shader cache options are really necessary. If there's not a use-case for being able to delete the precompiled caches specifically besides a MoltenVK issue (where a proper fix would be preferred to cluttering a menu with an additional option) it should be reduced to a singular option that just deletes all caches.

I also think the confirmation prompt is unnecessary. Graying out the deletion option makes more sense to me then having a prompt that shows whether deletion failed due to no cache existing.

**Comment by SSimco** [comment]
> The Open Cemu folder option was long overdue indeed so it's nice to see it being PRed.
> 
> I do wonder if three shader cache options are really necessary. If there's not a use-case for being able to delete the precompiled caches specifically besides a MoltenVK issue (where a proper fix would be preferred to cluttering a menu with an additional option) it should be reduced to a singular option that just deletes all caches.
> 
> I also think the confirmation prompt is unnecessary. Graying out the deletion option makes more sense to me then having a "no shader cache was found" prompt inside the code.

I merged the three options into one and it should disable it if no caches are found.

**Comment by Crementif** [comment]
Looks good, thanks!

**Pull request merged**
