### PR TITLE
Update GeneralSettings2.cpp: Add "and size"

### PR DESCRIPTION
**Pull request by davidhedlund**
Added "and size" to "Remember pad window position and size"

### CODE REVIEW

**Comment by Exzap** [comment]
Thanks for the pull request. I am not sure if we should merge this as-is because to me it looks off now because of how long the text is:
image

versus before:
image

Maybe there is a way to phrase it more concisely?

**Comment by davidhedlund** [comment]
> Thanks for the pull request. I am not sure if we should merge this as-is because to me it looks off now because of how long the text is: image
> 
> versus before: image
> 
> Maybe there is a way to phrase it more concisely?

How about "Remember main window position/size"?

**Comment by davidhedlund** [comment]
Please review the latest commit

**Comment by Exzap** [comment]
Using slashes in UI text is problematic for readability and localization.
I thought about it some more and I believe the original text is ok for now. Maybe I can come up with something better in the future.
At any rate, the tooltip explains that it also affects the window size and in the 7 years of troubleshooting I have done nobody ever was confused about the phrasing of this option so I don't think this really needs to be changed anyway.

Thanks for taking the time to submit the issue and PR

**Pull request closed without merging**
