### PR TITLE
Fixes Path Issues

### PR DESCRIPTION
**Pull request by ArtemisX64**
Fixes path issues in *nix
Need to confirm on Windows
Fixes https://github.com/cemu-project/Cemu/issues/65

### CODE REVIEW

**Comment by Wunkolo** [comment]
Looks like a use-case for [std::filesystem::path](https://en.cppreference.com/w/cpp/filesystem/path).

**Comment by ArtemisX64** [comment]
@Wunkolo Do I really need to use std::filesystem::path ? (Since windows already supports / for paths)

**Comment by Wunkolo** [comment]
It would allow for stuff like `blah / "usr" / "title" / fmt::format(...)` and the platform would handle the `/` and `\` automatically and might handle stuff like unicode characters or long paths better.

If windows already handles `/` safely and predictably already then yeah there is no need to.

**Comment by ArtemisX64** [comment]
@Wunkolo Makes sense using std::filesystem::path. I will correct my PR accordingly

**Comment by ArtemisX64** [comment]
@Wunkolo and @Exzap Can you review the code?

**Comment by ArtemisX64** [comment]
@Exzap ready for review

**Comment by Exzap** [comment]
Using std::filesystem::path seems unnecessarily verbose when forward slashes work just fine on any platform we might target. But more importantly this function should also work for Wii U internal paths where forward slashes are required.

**Comment by ArtemisX64** [comment]
> Using std::filesystem::path seems unnecessarily verbose when forward slashes work just fine on any platform we might target. But more importantly this function should also work for Wii U internal paths where forward slashes are required.

fixed

**Pull request merged**
