### PR TITLE
nsyshid: Emulate Infinity Base

### PR DESCRIPTION
**Pull request by deReeperJosh**
Following on from https://github.com/cemu-project/Cemu/pull/971, I am bringing the emulated Infinity Base that I created for Dolphin and RPCS3 here to Cemu. Currently the games all require the erreula.rpl and title files for erreula to launch, and will error if the files required for online play aren't present either. I have tested launching in to 1.0 successfully on my Mac, however because of the issues with Geometry Shader Conversion I am unable to actually play the games, but I am actively testing on my Windows machine everything works as expected there too. Will partly close https://github.com/cemu-project/Cemu/issues/588

### CODE REVIEW

**Comment by Edgerunner7** [comment]
Managed to get my hands on all the character files, tried playing the game on pc version with the gf but it doesn't have co-op, tried RPCS3 but I don't feel like ruining my eyes, Cemu has worked for all the laggy games and it seems to work for Disney Infinity but no one has anything on a cemu emulated base which led me here, so how far along is it and when do you think it will work properly?

**Comment by deReeperJosh** [comment]
@Edgerunner7 well you should be able to play the games with the builds on this PR, you will just need the erreula title files from your wii u. You also shouldn't need the character files because you can make your own in the emulated base dialog window, but if you want to use your own they should also work. If you want to be a tester on this pr, you can try one of the builds here: https://github.com/cemu-project/Cemu/actions/runs/9758278472?pr=1246

**Comment by Edgerunner7** [comment]
Thanks, I've got all 3 games on cemu so I'll test them and let you know how it goes, I've been a tester for games before so I'll be taking notes for any improvements.

**Comment by Edgerunner7** [comment]
The erreula title files might be its own problem, looks to be one of those agreements you agree to when you want to connect to their online server, seems a bit too complicated to put all 3 games in offline mode or find a bypass, I'll keep looking.

**Comment by Edgerunner7** [comment]
I've connected my Wii account letting me go online and accept the Eula, I did, now I have a different erreula, ErrEula:102-9999. I've checked other things that needed online services like Mario kart online play that gave ErrEula when you played online, it lets me connect now, bit stuck on DI atm

**Comment by deReeperJosh** [comment]
Did you dump the erreula rpl from your Wii U? I was able to accept the erreula error message and continue once I had

**Comment by deReeperJosh** [comment]
See here: [System RPL Files](https://wiki.cemu.info/wiki/System_RPL_Files)

**Comment by Edgerunner7** [comment]
Is the rpl specific to each console, and can you get it from anywhere else?
Because I think I just blew up the one console is had. Are the files the type that someone else has that I can get from them or does it have to be from this console account?

**Comment by deReeperJosh** [comment]
You have to dump them from a Wii U using the information on the link I shared

**Comment by Edgerunner7** [comment]
I understand what to do from the link, my problem is getting the rpl files, not sure what went wrong but its not letting me extract more files, I had it modded so it should work but the whole console is malfunctioning after i took out the first set of files for online mode on cemu.

**Comment by deReeperJosh** [comment]
As long as you didn't remove them from the console and just copied and pasted them you should be fine

**Comment by Edgerunner7** [comment]
I think I bricked mine, ordering another one, should be here in 2 days, thought I was copying but it was moving them.

**Comment by deReeperJosh** [comment]
Can you send screenshots of the error you are seeing? And did you also add the erreula title files as well as the rpl file?

**Comment by Edgerunner7** [comment]
That one is on DI 1.0, it gives me different error codes for each one

**Comment by deReeperJosh** [comment]
From the Wii U, located at mlc01/sys/title/0005001b/10051000

**Comment by Edgerunner7** [comment]
I don't have that last file
Screenshot 2024-07-11 155452

**Comment by deReeperJosh** [comment]
It should be a folder on your wii u, you will need to copy it across to Cemu

**Comment by Edgerunner7** [comment]
Success!!!, I managed to bypass the erreula, but when I start the game tutorial where the narrator starts talking, its a black screen, on all 3 games

**Comment by Edgerunner7** [comment]
Got on the spiderman playset, managed to skip the tutorial for 2.0, but when it reaches the point to put a figure down i get this message, also when you use the avengers playset it uses spiderman's instead and when you use an avengers character to move playsets it doesn't let you change.
Screenshot 2024-07-14 084815

**Comment by Edgerunner7** [comment]
Swapped to the GOTG playset an its all black screen and then it crashed before I could load a character. The spiderman playset only had black screen at the point of placing the character.

**Comment by deReeperJosh** [comment]
Strange, might just be not very well emulated in Cemu at the moment

**Comment by Exzap** [comment]
Looks good to me. Thanks!

**Pull request merged**
