### PR TITLE
Compile Unix Public release with -O2

### PR DESCRIPTION
**Pull request by bitscher**

### CODE REVIEW

**Comment by bitscher** [comment]
Actually the change seems to break LTO.

**Comment by bitscher** [comment]
My bad `-O3` is already present when compiling with `-DPUBLIC_RELEASE` hence why it was breaking at link time due to LTO.

**Comment by Exzap** [comment]
Optimization flags are already covered by using cmake CMAKE_BUILD_TYPE `Release` or `RelWithDebInfo`. It's not something you should manually override except maybe for non-standard flags like we do for MSVC.

**Comment by bitscher** [comment]
I noticed that yes.
I am really not familiar with CMAKE :)

**Pull request closed without merging**
