### PR TITLE
Always set GDK_BACKEND=x11

### PR DESCRIPTION
**Pull request by jn64**
[Workaround for Wayland](https://github.com/cemu-project/Cemu/issues/92#issue-1353130696). No effect on X11.

Should be fine to add it for everyone, [pcsx2 has had it for 6 years](https://github.com/PCSX2/pcsx2/commit/8958b2042fc1877617dcdcc335b8a0f082e2ca89).

### CODE REVIEW

**Comment by qurious-pixel** [comment]
I think this should be handled differently.
The appimage has this scripted in, but this will have to be reversed if a Wayland PR is merged.

**Comment by jn64** [comment]
Yes of course, it should be reverted once Wayland support is in.

I could not find anything in the AppImage build referencing this.

**Comment by qurious-pixel** [comment]
AppDir > apprun-hooks > linuxdeploy-plugin-gtk.sh

```
#! /usr/bin/env bash

gsettings get org.gnome.desktop.interface gtk-theme 2> /dev/null | grep -qi "dark" && GTK_THEME_VARIANT="dark" || GTK_THEME_VARIANT="light"
APPIMAGE_GTK_THEME="${APPIMAGE_GTK_THEME:-"Adwaita:$GTK_THEME_VARIANT"}" # Allow user to override theme (discouraged)

export APPDIR="${APPDIR:-"$(dirname "$(realpath "$0")")"}" # Workaround to run extracted AppImage
export GTK_DATA_PREFIX="$APPDIR"
export GTK_THEME="$APPIMAGE_GTK_THEME" # Custom themes are broken
export GDK_BACKEND=x11 # Crash with Wayland backend on Wayland
export XDG_DATA_DIRS="$APPDIR/usr/share:/usr/share:$XDG_DATA_DIRS" # g_get_system_data_dirs() from GLib
export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"
export GI_TYPELIB_PATH="$APPDIR/usr/lib/x86_64-linux-gnu/girepository-1.0"
export GTK_EXE_PREFIX="$APPDIR/usr"
export GTK_PATH="$APPDIR/usr/lib/x86_64-linux-gnu/gtk-3.0"
export GTK_IM_MODULE_FILE="$APPDIR/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache"

export GDK_PIXBUF_MODULE_FILE="$APPDIR//usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export LC_ALL=C
```

**Comment by jn64** [comment]
So... this script run all the time? i.e. they always set this because GTK-based AppImages would crash on Wayland without it?

**Comment by jn64** [comment]
I see the AppImage build fails because it thinks `env` is the program. Not related to earlier comments.

We can just patch it out in appimage.sh.

**Comment by jn64** [comment]
https://github.com/cemu-project/Cemu/pull/560/commits/d4aa05723f73aeb10a06579c8d1f3c7343d8e8ce fixed the AppImage build

- [previous point of failure](https://github.com/cemu-project/Cemu/actions/runs/3634986066/jobs/6133773684#step:5:1484)
- [same point in the new build](https://github.com/cemu-project/Cemu/actions/runs/3638845191/jobs/6141722806#step:5:1484)

So this way:

- no change for AppImage
- all other Linux builds (Ubuntu here, self builds, and downstream packages) get this change. Of the 3 AUR packages I'm aware of, only 1 currently patches this in, so the other 2 will benefit.

**Comment by Exzap** [comment]
This should no longer be necessary with #553 now merged? Although I'm not sure if OpenGL needs any wayland-specific setup code still.

**Comment by jn64** [comment]
Didn't know it was ready. Should have done this a few months ago :laughing:

**Pull request closed without merging**
