### PR TITLE
windows-build-error-fix

### PR DESCRIPTION
**Pull request by fuhongcui**
update vcpkg for windows build

### CODE REVIEW

**Comment by Squall-Leonhart** [comment]
This is a duplicate of https://github.com/cemu-project/Cemu/pull/1048, Exzap prefers to handle vcpkg updates internally.

**Comment by fuhongcui** [comment]
> What exactly are you fixing here? Cemu already builds on Windows.

The submodule vcpkg version in the current code has dependencies on libraries that are no longer present on the server.

image
image

**Comment by Squall-Leonhart** [comment]
Ah, i see, this only affects mingw builds then, but not msvc builds.

**Comment by fuhongcui** [comment]
> > Ah, i see, this probably only affects mingw builds then, but not msvc builds - i just built cemu just fine with msvc without any failures.
> 
> 
> 
> It does in fact affect MSVC use.
> 
> Building may be fine, CMake configuration is not, because the vcpkg download keeps failing. You probably already have the dependency downloaded from an earlier configuration

Yes, that's the issue I've encountered.

**Comment by Exzap** [comment]
Superseded by #1064

**Pull request closed without merging**
