### PR TITLE
Disable Discord checkbox based on build option

### PR DESCRIPTION
**Pull request by jn64**
Disable the Discord checkbox when compiled with `-DENABLE_DISCORD_RPC=OFF`.

I'm not a programmer (but I play one on TV), so please let me know where the code should go if not here.

screenshot

### CODE REVIEW

**Comment by jn64** [comment]
> If true the check box should not be clickable also.

I don't know what you mean.

**Comment by Masamune3210** [comment]
They mean the checkbox next to the greyed out option should be disabled as well to prevent people from enabling it

**Comment by Exzap** [comment]
The text being grayed out means the checkbox is disabled. Box and text are part of the same checkbox widget

Anyway LGTM. Thanks!

**Comment by Masamune3210** [comment]
Aah, I see. Thanks for the info

**Pull request merged**
