### PR TITLE
[LINUX] Build Source Libs

### PR DESCRIPTION
**Pull request by qurious-pixel**
Builds Linux libs from source rather than VCPKG.
Caches the builds to speed-up subsequent builds.

Fixes [779](https://github.com/cemu-project/Cemu/issues/779), [763](https://github.com/cemu-project/Cemu/issues/763), [722](https://github.com/cemu-project/Cemu/issues/722)

**EDIT:** Added easier VCPKG build with Conditional switch

### CODE REVIEW

**Comment by jn64** [comment]
I'm not sure how this fixes #781. My Fedora Copr builds would not be affected by changes to the github builds.

**Comment by qurious-pixel** [comment]
> I'm not sure how this fixes #781. My Fedora Copr builds would not be affected by changes to the github builds.

I may have jumped to quickly on the source of the error, but those were the error messages printed on console for Fedora 38 that I had prior to this PR build.

**Comment by Tachi107** [comment]
I'm not sure this is an appropriate fix for Cemu. Not only this works around the vcpkg package manager used by the CMake build system, but this avoids the build system completely by running a single script. Talking about the script, installing things into `/usr` without involving the system package manager might break the system.

I appreciate your efforts in fixing things for Linux users, but what I'm trying to say is that maybe this isn't the right approach; if there are issues in vcpkg's packages, they should be fixed there.

**Comment by qurious-pixel** [comment]
Superceded by https://github.com/cemu-project/Cemu/pull/784

**Pull request closed without merging**
