### PR TITLE
cmake: exclude fmt10

### PR DESCRIPTION
**Pull request by abouvier**
Related to https://github.com/cemu-project/Cemu/issues/919 and https://github.com/cemu-project/Cemu/issues/920.

### CODE REVIEW

**Comment by Exzap** [comment]
Interesting that this works. Thanks for the contribution!

**Comment by Exzap** [comment]
Does this actually fix the issue on arch? I was under the impression that only fmt 10 is available now

**Comment by abouvier** [comment]
No, but I created a [fmt9](https://aur.archlinux.org/packages/fmt9) package on the AUR in the meantime. But if you have both `fmt` and `fmt9` installed, CMake will pick the fmt10 version without this fix because fmt actually [accept anything](https://github.com/fmtlib/fmt/blob/757564f5cd2fa78b634dd698c63dbf069818e6fd/CMakeLists.txt#L366).

**Comment by alba4k** [comment]
This is still a workaround however, as forcing an old library version is not a solution (in the long term)

**Pull request merged**
