### PR TITLE
Added Arch and Fedora deps and changed Ubuntu deps location

### PR DESCRIPTION
**Pull request by RyzenDew**
Updated linux Build instructions with Arch deps

### CODE REVIEW

**Comment by zjeffer** [comment]
Have you managed to build this without errors on Arch? I tried with clang13 which didn't work (see #17). Currently Arch doesn't have clang12 which isn't included in your dependency installation.

**Comment by RyzenDew** [comment]
> 

no but they needed to be added just like fedora

**Comment by Nefsen402** [comment]
For arch there doesn't seem to be too much to screw with in terms of VULKAN_SDK. As long as the `vulkan-devel` meta package is installed (pretty sure it can be trimmed down to only a few packages) and setting the environment variable to `/usr` will work without pulling down stuff from a untrusted source.

**Comment by throwaway1037** [comment]
Woah, why does `systemd` need to be installed? Does this need to be a new issue to add support for non-systemd systems?

**Comment by bbaster** [comment]
Why include the distro-agnostic build steps again? IMO something like this would be better:

```
For Ubuntu and most derivatives:

`sudo apt install -y libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev freeglut3-dev clang-12 nasm`

For Arch and most derivatives:

`sudo pacman -S --needed gtk3 libsecret libgcrypt systemd-libs freeglut nasm`

1) Make sure vulkansdk is installed and the VULKAN_SDK environment variable is set correctly.
2) Run `git clone --recursive https://github.com/cemu-project/Cemu`
3) `cd Cemu`
4) `mkdir build && cd build`
5) `cmake .. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/bin/clang-12 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja`
6) `ninja`
```

**Comment by beneregesh** [comment]
Arch currently  does not have clang-12 or clang++-12. The mainline version is 14 so this won't work:
```5) `cmake .. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/bin/clang-12 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja`
```

**Comment by RyzenDew** [comment]
> 

this is wip we are changing as we go and that was already changed

**Comment by RyzenDew** [comment]
> Why include the distro-agnostic build steps again? IMO something like this would be better:
> 
> ```
> For Ubuntu and most derivatives:
> 
> `sudo apt install -y libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev freeglut3-dev clang-12 nasm`
> 
> For Arch and most derivatives:
> 
> `sudo pacman -S --needed gtk3 libsecret libgcrypt systemd-libs freeglut nasm`
> 
> 1) Make sure vulkansdk is installed and the VULKAN_SDK environment variable is set correctly.
> 2) Run `git clone --recursive https://github.com/cemu-project/Cemu`
> 3) `cd Cemu`
> 4) `mkdir build && cd build`
> 5) `cmake .. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/bin/clang-12 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja`
> 6) `ninja`
> ```

i will be cleaning it all up in a min

**Comment by bbaster** [comment]
I think `git` and `ninja` should be included too. Also when `vcpkg`'s dependencies are unmet it generates a log file with the following contents:

```
Could not find zip. Please install it (and other dependencies) with:
On Debian and Ubuntu derivatives:
  sudo apt-get install curl zip unzip tar
On recent Red Hat and Fedora derivatives:
  sudo dnf install curl zip unzip tar
On older Red Hat and Fedora derivatives:
  sudo yum install curl zip unzip tar
On SUSE Linux and derivatives:
  sudo zypper install curl zip unzip tar
On Arch Linux and derivatives:
  sudo pacman -S curl zip unzip tar cmake ninja
On Alpine:
  apk add build-base cmake ninja zip unzip curl git
  (and export VCPKG_FORCE_SYSTEM_BINARIES=1)
```

**Comment by RyzenDew** [comment]
> I think `git` and `ninja` should be included too. Also when `vcpkg`'s dependencies are unmet it generates a log file with the following contents:
> 
> ```
> Could not find zip. Please install it (and other dependencies) with:
> On Debian and Ubuntu derivatives:
>   sudo apt-get install curl zip unzip tar
> On recent Red Hat and Fedora derivatives:
>   sudo dnf install curl zip unzip tar
> On older Red Hat and Fedora derivatives:
>   sudo yum install curl zip unzip tar
> On SUSE Linux and derivatives:
>   sudo zypper install curl zip unzip tar
> On Arch Linux and derivatives:
>   sudo pacman -S curl zip unzip tar cmake ninja
> On Alpine:
>   apk add build-base cmake ninja zip unzip curl git
>   (and export VCPKG_FORCE_SYSTEM_BINARIES=1)
> ```

ok tell me what to add the whole list

**Comment by bbaster** [comment]
> ok tell me what to add the whole list

Replace the dependencies part of your BUILD.md with the following, I've added deps required by `vcpkg` as well as `git`, `cmake`, and `ninja` as they are used in the build steps:

```
For Ubuntu and most derivatives:

`sudo apt install -y libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev freeglut3-dev clang-12 nasm curl zip unzip tar git cmake ninja-build`

For Arch and most derivatives:

`sudo pacman -S --needed gtk3 libsecret libgcrypt systemd-libs freeglut nasm curl zip unzip tar git cmake ninja`

For Fedora and most derivatives:

`sudo dnf in -y gtk3-devel libsecret-devel libgcrypt-devel systemd-devel freeglut-devel nasm cmake vcpkg perl-core zlib-devel curl zip unzip tar git cmake ninja-build`
```

Also are `vcpkg`, `perl-core` and `zlib-devel` really required on Fedora? I don't see similar dependencies for Arch and Ubuntu, maybe they can be dropped?

**Comment by RyzenDew** [comment]
> > ok tell me what to add the whole list
> 
> Replace the dependencies part of your BUILD.md with the following, I've added deps required by `vcpkg` as well as `git`, `cmake`, and `ninja` as they are used in the build steps:
> 
> ```
> For Ubuntu and most derivatives:
> 
> `sudo apt install -y libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev freeglut3-dev clang-12 nasm curl zip unzip tar git cmake ninja-build`
> 
> For Arch and most derivatives:
> 
> `sudo pacman -S --needed gtk3 libsecret libgcrypt systemd-libs freeglut nasm curl zip unzip tar git cmake ninja`
> 
> For Fedora and most derivatives:
> 
> `sudo dnf in -y gtk3-devel libsecret-devel libgcrypt-devel systemd-devel freeglut-devel nasm cmake vcpkg perl-core zlib-devel curl zip unzip tar git cmake ninja-build`
> ```
> 
> Also are `vcpkg`, `perl-core` and `zlib-devel` really required on Fedora? I don't see similar dependencies for Arch and Ubuntu, maybe they can be dropped?

fedoras included git unzip and curl zip tar and yes the rest are needed it's why they where added

**Comment by RyzenDew** [comment]
same goes for arch it comes with curl zip unzip tar

**Comment by bbaster** [comment]
> same goes for arch it comes with curl zip unzip tar

You are right about `tar` and `curl`, `tar` is a part of the `base` group and `curl` is a dependency of `pacman`, but `zip` and `unzip` aren't a part of the default install, I had to install `zip` manually - here's the package statistics for [zip](https://pkgstats.archlinux.de/packages/zip) and [unzip](https://pkgstats.archlinux.de/packages/unzip).

`cmake` and `ninja` are still missing from the Arch deps, I'm not sure whether `git` and `ninja-build` are preinstalled on Fedora.

**Comment by RyzenDew** [comment]
> > same goes for arch it comes with curl zip unzip tar
> 
> You are right about `tar` and `curl`, `tar` is a part of the `base` group and `curl` is a dependency of `pacman`, but `zip` and `unzip` aren't a part of the default install, I had to install `zip` manually - here's the package statistics for [zip](https://pkgstats.archlinux.de/packages/zip) and [unzip](https://pkgstats.archlinux.de/packages/unzip).
> 
> `cmake` and `ninja` are still missing from the Arch deps, I'm not sure whether `git` and `ninja-build` are preinstalled on Fedora.

zip and unzip are default with gnome and kde installs they come with it due to having archiver program and ark and yes git is preinstalled on fedora since fedora 32 and ninja comes with another package vcpkg so all is good

**Comment by bbaster** [comment]
> zip and unzip are default with gnome and kde installs they come with it due to having archiver program and ark and yes git is preinstalled on fedora since fedora 32 and ninja comes with another package vcpkg so all is good

`zip` and `unzip` aren't dependencies of KDE's Ark, even if they were not all Arch Linux use either KDE Plasma or GNOME, many use other desktop environments and window managers. Look at the package statistics of `zip` and `unzip` I provided earlier, they aren't 100%

**Comment by tinyzimmer** [comment]
The steps in this PR are getting me _almost_ all the way on Arch now. I'm failing at the final linking step with:

```
/usr/bin/ld: cannot open output file src/Cemu: Is a directory
```

Which makes sense to me, because it is in fact a directory. I'm just unsure how to configure it to try to output somewhere else.

**Comment by tinyzimmer** [comment]
Ah, adding `-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin` to the `cmake` command took care of that for me I think. Not sure why the default for that is the src directory.

**Pull request closed without merging**
