### PR TITLE
Add support for non portable mode

### PR DESCRIPTION
**Pull request by SSimco**
Now the app name is `Cemu` instead of `cemu`.

### CODE REVIEW

**Comment by kturques** [comment]
Don't know if this is the right place to comment, but "gameProfiles" are not getting saved. This should go in "$XDG_CONFIG_HOME/Cemu/gameProfiles"

**Comment by SSimco** [comment]
> Don't know if this is the right place to comment, but "gameProfiles" are not getting saved. This should go in "$XDG_CONFIG_HOME/Cemu/gameProfiles"

It wasn't saving because it was not creating a `gameProfiles` folder. Also, it was trying to save `gameProfiles` to `$XDG_DATA_HOME/Cemu/gameProfiles`.

I changed it now so it saves to `$XDG_CONFIG_HOME/Cemu/gameProfiles` and it creates the folder if it doesn't exist.

**Comment by Exzap** [comment]
Looks good now. Thanks!

**Comment by emiyl** [comment]
In the original PR (#316), it says the macOS config and user data paths should be at `~/Library/Application Support/Cemu`, however this is not the case. In this PR, config files are stored in `~/.config/Cemu` and user data files are stored `/.local/share/Cemu` on macOS, same as Linux. Is this intentional?

**Comment by emiyl** [comment]
> No, it's not intentional. Maybe BOOST_OS_LINUX is defined somehow and it's using the paths for Linux?

Yes, there should be an extra check for BOOST_OS_MACOS when setting paths.

**Comment by Tatsh** [comment]
This does not cover everything that #130 was covering since when I start Cemu, it immediately shows this and hangs:

image

With #130 this was not the case and the Cemu binary could live anywhere as long as system data paths were known. There should not be a need to have a wrapper that would set up the correct working directory before execution, assuming that is the workaround here.

**Pull request merged**
