### PR TITLE
Proper fix for static asserts

### PR DESCRIPTION
**Pull request by ArtemisX64**
Uses uniform_int_distribution function provided by boost::random instead of relying on standard library in systems other than Windows
It fixes https://github.com/cemu-project/Cemu/issues/48

### CODE REVIEW

**Comment by Exzap** [comment]
I think it would be better if we put something like this into precompiled.h:
```
// workaround for a compile error with certain combos of Linux compilers and STL
#if BOOST_OS_LINUX
#include <boost/random/uniform_int.hpp>
namespace std_rd_workaround = boost::random;
#else
namespace std_rd_workaround = std;
#endif
```
And then in the .cpp files just replace `std::uniform_int_distribution` with `std_rd_workaround::uniform_int_distribution` instead of having all those #if-#else. It also keeps the workaround a bit more centralized

But since you added boost-random to vcpkg we may as well just use boost::random on all platforms and call it a day.

**Comment by ArtemisX64** [comment]
> I think it would be better if we put something like this into precompiled.h:
> 
> ```
> // workaround for a compile error with certain combos of Linux compilers and STL
> #if BOOST_OS_LINUX
> #include <boost/random/uniform_int.hpp>
> namespace std_rd_workaround = boost::random;
> #else
> namespace std_rd_workaround = std;
> #endif
> ```
> 
> And then in the .cpp files just replace `std::uniform_int_distribution` with `std_rd_workaround::uniform_int_distribution` instead of having all those #if-#else. It also keeps the workaround a bit more centralized
> 
> But since you added boost-random to vcpkg we may as well just use boost::random on all platforms and call it a day.

Ok

**Comment by Tachi107** [comment]
Why is the standard random number generator causing issues?

**Comment by ArtemisX64** [comment]
> Why is the standard random number generator causing issues?

Currently, I can't pinpoint the real issue. (Also, because my laptop is slow, large compilation times). Most likely related with the build environment because outside of it, it compiles fine. (Verifed using clang++ and g++ using libstdc++12 and libc++14). But I think using the boost random generator is better than disabling static asserts in general

**Comment by ArtemisX64** [comment]
@Exzap Can you review the change?

**Comment by Tachi107** [comment]
> Currently, I can't pinpoint the real issue. (Also, because my laptop is slow, large compilation times). Most likely related with the build environment because outside of it, it compiles fine. (Verifed using clang++ and g++ using libstdc++12 and libc++14). But I think using the boost random generator is better than disabling static asserts in general

I instead think that the static assert could instead be telling us that there is a real issue in the code... Are you able to reproduce this with a minimal example? Possibly on compiler-explorer.com so that I can see the error too?

**Comment by ArtemisX64** [comment]
@Tachi107 https://compiler-explorer.com/z/rbPP7Mdz1

**Comment by Tachi107** [comment]
This is odd. Are you able to show the output of the static_assert?

**Comment by Crementif** [comment]
I'd prefer to extract the ubuntu audio change out of this PR. Could you make it a separate PR cuz it's a great change otherwise?

**Comment by ArtemisX64** [comment]
> I'd prefer to extract the pulseaudio-dev CI change out of this PR. Could you make it a separate PR cuz it's a great change otherwise?

OOps my bad. Made to run in my localized repo. I will make the change

**Comment by ArtemisX64** [comment]
@Tachi107 
```
static_assert(!_Up_traits::__is_signed, "U must be unsigned");
static_assert(!_Wp_traits::__is_signed, "W must be unsigned");
```
This was the static_asserts we were getting

**Comment by Tachi107** [comment]
@ArtemisX64 

> ```
> static_assert(!_Up_traits::__is_signed, "U must be unsigned");
> static_assert(!_Wp_traits::__is_signed, "W must be unsigned");
> ```
> 
> This was the static_asserts we were getting with cemu(When calling generators)

Stupid question: does explicitly using `U` fixes the issue?

```cpp
std::uniform_int_distribution<decltype(characters.size())> index_dist(0U, characters.size() - 1U);
```

**Comment by ArtemisX64** [comment]
@Tachi107 Nope. Still the same static_assert. (Tried now). Yesterday, I explicitly created two variables to check it and I had the same issue.(Only with Cemu)

**Comment by ArtemisX64** [comment]
> This is really odd, and really interesting too. This only happens on Clang 14 and above, right? 
My findings is it happens on latest libstdc++ version. (Which makes sense since it compiles on Ubuntu 20.04 and not on other systems with latest libstdc++12 and clang12 and iirc, new version added static_assert patch which is harmless in general)
>And only with libstdc++ or also with libc++?
It failes to compile with libc++ because of WxWidgets iirc. (Tried once)

**Comment by ArtemisX64** [comment]
I am planning on making it compile on g++. But at first, I have to deal with dllexports. (Or -fms-extensions flag or windows only functions in general). Do you know any alternatives for -fms-extensions flag for gcc?

**Comment by ArtemisX64** [comment]
@Exzap I think it is ready to be merged.

**Comment by Tachi107** [comment]
Could you point me to the "dllexport" code? I think I know how to deal with it, but maybe I'm thinking at something else

**Comment by ArtemisX64** [comment]
> Could you point me to the "dllexport" code? I think I know how to deal with it, but maybe I'm thinking at something else

The fix is simple. What I need is not to do it for now. (Since I don't know how to replace _umul64() )

**Comment by ArtemisX64** [comment]
@Tachi107 You can find them by disabling -fms-extensions flag

**Comment by Exzap** [comment]
One last nitpick: Please start single-line comments with a lowercase letter and a leading space to match the rest of the codebase. 
E.g. `// use boost ...` instead of `//Use boost ...`
Everything else is ok and I'll merge it after you change the comments. Thanks for this improved workaround!

**Pull request merged**
