### PR TITLE
Added Native Pretendo and custom URLs support

### PR DESCRIPTION
**Pull request by MythicalPlayz**
This PR adds support for third party servers (currently Pretendo only but can be expanded later) support natively and Indication on top of which Network Service the user is using.

This also Adds an option to disable SSL Verification checkbox if third party servers do not have SSL (like Pretendo atm).

### CODE REVIEW

**Comment by MythicalPlayz** [comment]
image
This is what the Account menu Looks

(if anyone can improve the placement of the new Items that would be great)

**Comment by jonbarrow** [comment]
Maybe it would be cleaner to replace the parts of the URL string during the request instead of returning new ones? This would likely reduce the number of checks needed. So when Cemu goes to make a request to the servers, do a check for the active then and run a replace on the URL to change `nintendo.net` to `pretendo.cc`?

**Comment by Alecerzea** [comment]
How can I download or compile these PR??

**Comment by MythicalPlayz** [comment]
Look in my Actions and find the compiled versions (Except MacOS)

**Review by Exzap — CHANGES_REQUESTED** [review]
Structurally this is pretty good and it integrates well with the existing config code.
Some smaller improvements can be made for cleaner code, see comments.

**Comment by latitudeh** [comment]
Any updates on when this will be merged?

**Review by Exzap — APPROVED** [review]

**Comment by Exzap** [comment]
LGTM. Not sure if the MacOS compilation error is resolved but if not it should be an easy fix which I will look into after merging.

**Pull request merged**
