### PR TITLE
Boost: Fix building against Boost 1.87.0

### PR DESCRIPTION
**Pull request by FireBurn**
Closes: https://github.com/cemu-project/Cemu/issues/1451

### CODE REVIEW

**Comment by FireBurn** [comment]
I think that's enough to get things building with boost 1.87.0

**Comment by Tatsh** [comment]
Thanks.

**Comment by AngryPenguinPL** [comment]
I can confirm, it fixed build with boost 1.87.0 for me.
Thanks.

**Comment by Exzap** [comment]
thanks!

**Pull request merged**
