### PR TITLE
Linux: Add Vulkan support for wayland

### PR DESCRIPTION
**Pull request by SSimco**

### CODE REVIEW

**Comment by amayra** [comment]
cemu crashed without a log file in Wayland when I chose Vulkan but I blamed my configuration or distro 

I never think that cemu don't fully support Wayland yet

**Comment by SSimco** [comment]
> cemu crashed without a log file in Wayland when I chose Vulkan but I blamed my configuration or distro
> 
> I never think that cemu don't fully support Wayland yet

Can you try running Cemu in a terminal and post the stack trace?

**Comment by SSimco** [comment]
I changed it so it will only have one of those extensions corresponding to what backend the main window has.

**Comment by amayra** [comment]
> > cemu crashed without a log file in Wayland when I chose Vulkan but I blamed my configuration or distro
> > I never think that cemu don't fully support Wayland yet
> 
> Can you try running Cemu in a terminal and post the stack trace?
> 
> It might not work on all configurations. I can't get it to run on my NVIDIA dGPU while it runs fine on the integrated GPU.

`(Cemu:476399): Gdk-CRITICAL **: 23:40:49.009: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

(Cemu:476399): Gtk-CRITICAL **: 23:40:49.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Cemu:476399): Gdk-CRITICAL **: 23:41:06.606: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
`

**Comment by SSimco** [comment]
> > > cemu crashed without a log file in Wayland when I chose Vulkan but I blamed my configuration or distro
> > > I never think that cemu don't fully support Wayland yet
> > 
> > 
> > Can you try running Cemu in a terminal and post the stack trace?
> > It might not work on all configurations. I can't get it to run on my NVIDIA dGPU while it runs fine on the integrated GPU.
> 
> `(Cemu:476399): Gdk-CRITICAL **: 23:40:49.009: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
> 
> (Cemu:476399): Gtk-CRITICAL **: 23:40:49.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> 
> (Cemu:476399): Gdk-CRITICAL **: 23:41:06.606: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed `

I don't think you are using the right version of Cemu, those errors would only show up if you used a version without this patch.

Try recompiling Cemu with the patch from this PR.

**Comment by amayra** [comment]
i used AUR version not appimage this least version Cemu 2.0-19 (Experimental)

but i don't know how to complied cemu with PR patch im still new to linux 

i will wait for it get add to master repo to test it again 

right now everything work fine X11 plus ryujinx and PPSSPP have some problems before

**Comment by Exzap** [comment]
This seems to create `wxWlSubsurface` only for the main window in `VulkanCanvas` constructor but not for the pad view window. Is this intentional?

**Comment by SSimco** [comment]
> This seems to create `wxWlSubsurface` in `VulkanCanvas` constructor only for the main window but not for the pad view window. Is this intentional?

Yes. I've done it that way because it would paint over the menus in the main window if I used the same surface, and the only workaround that I've found is to make a new surface, that has the role of a subsurface, and offset its position with the position of the `VulkanCavas`.

Since the pad view creates a new frame that doesn't have a menu bar, it doesn't matter on what surface it draws on.

**Pull request merged**
