### PR TITLE
Add the missing decoders on MacOS. Testing finished

### PR DESCRIPTION
**Pull request by Tillsunset**
It is currently separated into different files to help speed up incremental build, when ready it will be cleaned up.

Decoders:
TextureDecoder_R5_G5_B5_A1_UNORM_swappedRB_torgba8888, replaces on MacOS TextureDecoder_R5_G5_B5_A1_UNORM_swappedRB.
TextureDecoder_A1_B5_G5_R5_UNORM_vulkan_toRGBA8888, replaces on MacOS TextureDecoder_A1_B5_G5_R5_UNORM_vulkan.

Testing needed:
Please comment which games use the texture format to be replaced and the in game situation the textures occur in.

### CODE REVIEW

**Comment by emiyl** [comment]
image

R5G5B5A1 decoder works perfectly

**Comment by Tillsunset** [comment]
good news, the dedicated decoders have been tested and now work.
bad news, VC64 which afaik are the only games that use TextureDecoder_A1_B5_G5_R5_UNORM_vulkan_To_RGBA8, is broken on macOS. Seems to an issue with string joining in moltenvk/SPIRV itself. So we won't be playing those games any time soon.

**Comment by Tillsunset** [comment]
Screen Shot 2022-10-07 at 5 26 37 PM
Screen Shot 2022-10-07 at 5 26 56 PM

**Comment by Exzap** [comment]
LGTM

**Pull request merged**
