### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by n0toose**
I would normally sort the files alphabetically, but I intuitively chose to go with the file type, somewhat, instead.

### CODE REVIEW

**Comment by Tachi107** [comment]
While you're updating stuff, you might want to put a leading slash `/` to most paths (basically anything other than the ones starting with `*.`), otherwise git will ignore files matching the patterns in any directory.

**Comment by n0toose** [comment]
Yeah, you're right about that.

**Comment by n0toose** [comment]
I can't really see in which case e.g. the `/bin/Cemu` directory would be in any other place other than the root of the project if documentation is to be followed, though. Are you sure about tha?

**Comment by Tachi107** [comment]
Yeah it generally shouldn't happen but I usually prefer to be explicit and avoid surprises (e.g. in the future Cemu might want to create a subdir named `bin/` in `src/`, and `src/bin/Cemu` will get ignored).

It's not important anyway, so you can simply leave things as they are. If the devs want to add `/` in the future they'll do it themself, I guess :)

**Comment by Exzap** [comment]
We already have these covered on a branch. Will be merged soon

**Pull request closed without merging**
